name: Update Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

steps:
  - name: Branch
    uses: juliangruber/update-pull-request-branch-action@v1
    with:
      number: 1
      github-token: ${{ secrets.GITHUB_TOKEN }}
