name: Update Branch

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  assignAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request
        uses: juliangruber/update-pull-request-branch-action@v1.0.1
        with:
          number: 1
          github-token: ${{ secrets.GITHUB_TOKEN }}
